import dayjs from 'dayjs/esm';
import { IFicha } from 'app/entities/ficha/ficha.model';

export interface IAlfa {
  id: number;
  parcela?: string | null;
  tipoTitular?: string | null;
  nomeTitular?: string | null;
  estadoSocial?: string | null;
  dataNascimento?: dayjs.Dayjs | null;
  sexo?: string | null;
  documento?: string | null;
  numeroDocumento?: string | null;
  datEmissao?: string | null;
  localEmissao?: string | null;
  contactoPrincipal?: string | null;
  contactoAlternativo?: string | null;
  estadoCivil?: string | null;
  nomeConjugue?: string | null;
  distritoMunicipal?: string | null;
  bairro?: string | null;
  quatreirao?: string | null;
  talhao?: string | null;
  celula?: string | null;
  bloco?: string | null;
  avenida?: string | null;
  numeroPolicia?: string | null;
  usoActual?: string | null;
  formaUso?: string | null;
  formaObtencao?: string | null;
  tipo?: string | null;
  anoOcupacao?: number | null;
  tipoAcesso?: string | null;
  conflito?: boolean | null;
  detalhesConflito?: boolean | null;
  construcaoPrecaria?: boolean | null;
  pisosAcimaSoleira?: number | null;
  pisosAbaixoSoleira?: number | null;
  materialConstrucaoBarrote?: boolean | null;
  materialConstrucaoIBR?: boolean | null;
  materialConstrucaoPranchas?: boolean | null;
  materialConstrucaoPau?: boolean | null;
  materialConstrucaoCanico?: boolean | null;
  materialConstrucaoCimento?: boolean | null;
  ocupacao?: string | null;
  TipoContrucao?: string | null;
  detalhesTipoContrucao?: string | null;
  infraestruturaExistente?: string | null;
  dataLevantamento?: dayjs.Dayjs | null;
  ficha?: Pick<IFicha, 'id' | 'processo'> | null;
}

export type NewAlfa = Omit<IAlfa, 'id'> & { id: null };
